
# resume information
resume-index = 13338
seed = 19678
rate = 1500      
shard = 1/1
nocapture = servername


adapter-ip = 192.168.4.196
# TARGET SELECTION (IP, PORTS, EXCLUDES)
ports = 139,445,2049
range = 85.137.0.0/16

